theme: jekyll-theme-cayman
plugins:
 - jekyll-relative-links
relative_links:
 enabled: true
 collections: true
title: Welcome to Drew Honson's homepage!
description: New projects and protocols posted here
include:
 - index.html
 - testpage.md
